import type { HomeHmsCycle, HomeStorePlan } from "@/types";

export type StoreComparisonRow =
  | { section: string }
  | { feature: string; free: boolean; standard: boolean; enterprise: boolean };

export const STORE_PLANS: HomeStorePlan[] = [
  {
    name: "Free",
    description: "For new businesses getting started.",
    priceDisplay: "N0",
    feeDisplay: "4% platform fee per order",
    features: [
      "Unlimited products",
      "Business website + PWA",
      "Paystack payment gateway",
      "Invoices, receipts, discounts",
      "Business analytics dashboard",
    ],
    ctaLabel: "Start with Free",
    ctaHref: "/register",
    featured: true,
  },
  {
    name: "Standard",
    description: "For growing businesses that want zero platform fees.",
    priceDisplay: "N10,000/mo",
    feeDisplay: "0% platform fee",
    features: [
      "Everything in Free",
      "Enhanced analytics",
      "Marketing tools",
      "Advanced export reports",
      "Priority customer support",
    ],
    ctaLabel: "Choose Standard",
    ctaHref: "/register",
  },
  {
    name: "Enterprise",
    description: "Custom support, integrations, and operational flexibility.",
    priceDisplay: "Custom",
    feeDisplay: "Configurable pricing",
    features: [
      "Everything in Standard",
      "Dedicated digital/IT support",
      "Custom automations",
      "Enterprise integrations",
      "SLA-backed support",
    ],
    ctaLabel: "Talk to Sales",
    ctaHref: "/contact",
  },
];

export const STORE_FEATURE_COMPARISON_ROWS: StoreComparisonRow[] = [
  { section: "Core & platform" },
  { feature: "Unlimited products", free: true, standard: true, enterprise: true },
  { feature: "Business website + PWA", free: true, standard: true, enterprise: true },
  { feature: "Paystack payment gateway", free: true, standard: true, enterprise: true },
  { feature: "4% platform fee per order", free: true, standard: false, enterprise: false },
  { feature: "0% platform fee", free: false, standard: true, enterprise: false },
  { feature: "Custom platform fee", free: false, standard: false, enterprise: true },
  { section: "Advanced analytics & reports" },
  { feature: "Sales trends, traffic & conversion metrics", free: true, standard: true, enterprise: true },
  { feature: "Exportable CSV/PDF reports", free: false, standard: true, enterprise: true },
  { feature: "Visual dashboards with charts", free: true, standard: true, enterprise: true },
  { section: "Progressive Web App (PWA)" },
  { feature: "Push notifications", free: false, standard: true, enterprise: true },
  { feature: "Offline browsing", free: true, standard: true, enterprise: true },
  { feature: "Add to home screen", free: true, standard: true, enterprise: true },
  { feature: "App-like experience for mobile", free: true, standard: true, enterprise: true },
  { section: "Custom domain" },
  { feature: "Link your own domain", free: false, standard: true, enterprise: true },
  { feature: "SSL certificate support", free: false, standard: true, enterprise: true },
  { feature: "Easy setup from dashboard", free: false, standard: true, enterprise: true },
  { section: "SEO & marketing tools" },
  { feature: "Meta tags management", free: true, standard: true, enterprise: true },
  { feature: "Social sharing integration", free: true, standard: true, enterprise: true },
  { feature: "Campaign tracking", free: false, standard: true, enterprise: true },
  { feature: "Newsletter & email marketing", free: false, standard: true, enterprise: true },
  { feature: "CRM tools for subscribers", free: false, standard: true, enterprise: true },
  { section: "Communication & notifications" },
  { feature: "Email notifications (orders, products, updates)", free: true, standard: true, enterprise: true },
  { feature: "In-app notifications for users", free: false, standard: true, enterprise: true },
  { feature: "SMS alerts (optional)", free: false, standard: true, enterprise: true },
  { feature: "Push notifications (PWA/mobile)", free: false, standard: true, enterprise: true },
  { section: "Discounts & promotions" },
  { feature: "Coupon codes", free: true, standard: true, enterprise: true },
  { feature: "Flash sales / limited-time offers", free: false, standard: true, enterprise: true },
  { feature: "Automatic discount rules", free: false, standard: true, enterprise: true },
  { section: "Shipping & tax" },
  { feature: "Multiple shipping carriers", free: false, standard: true, enterprise: true },
  { feature: "Tax rules per region", free: true, standard: true, enterprise: true },
  { feature: "Automated shipping cost calculation", free: false, standard: true, enterprise: true },
  { section: "Team & staff management" },
  { feature: "Multiple user accounts", free: false, standard: true, enterprise: true },
  { feature: "Role-based access control", free: false, standard: true, enterprise: true },
  { feature: "Activity logs & audit trail", free: false, standard: true, enterprise: true },
  { section: "Integrations & API" },
  { feature: "Third-party apps (ERP, CRM, analytics)", free: false, standard: true, enterprise: true },
  { feature: "Webhooks for automation", free: false, standard: true, enterprise: true },
  { feature: "Payment gateways beyond Paystack", free: false, standard: false, enterprise: true },
  { feature: "Enterprise API access", free: false, standard: false, enterprise: true },
  { section: "Payments & checkout" },
  { feature: "Multiple payment methods", free: true, standard: true, enterprise: true },
  { feature: "Saved cards for repeat customers", free: true, standard: true, enterprise: true },
  { feature: "Split payments & multi-currency", free: false, standard: true, enterprise: true },
  { feature: "Payment notifications for merchants", free: true, standard: true, enterprise: true },
  { section: "Support" },
  { feature: "Priority / dedicated support", free: false, standard: true, enterprise: true },
  { feature: "Enhanced analytics & marketing tools", free: false, standard: true, enterprise: true },
  { feature: "Enterprise tools & custom integrations", free: false, standard: false, enterprise: true },
];

export const HMS_CYCLES: HomeHmsCycle[] = [
  {
    id: "monthly",
    label: "Monthly",
    badge: null,
    priceDisplay: "N200,000",
    period: "/month",
    feeDisplay: "Billed monthly",
    total: "N2,400,000/yr",
    ctaLabel: "Start 14-Day Free Trial",
  },
  {
    id: "quarterly",
    label: "Quarterly",
    badge: "Save 8%",
    priceDisplay: "N550,000",
    period: "/quarter",
    feeDisplay: "Billed every 3 months",
    total: "N2,200,000/yr",
    ctaLabel: "Start 14-Day Free Trial",
  },
  {
    id: "yearly",
    label: "Yearly",
    badge: "Best Value — Save 17%",
    priceDisplay: "N2,000,000",
    period: "/year",
    feeDisplay: "Billed annually",
    total: "N166,667/mo effective",
    ctaLabel: "Start 14-Day Free Trial",
    featured: true,
  },
];

export const HMS_FEATURES = [
  "Front Desk & Check-in / Check-out",
  "Reservation Management",
  "Real-time Room Status Board",
  "Guest Directory & Profiles",
  "Loyalty Points System",
  "Housekeeping Module",
  "Kitchen / F&B Orders",
  "Maintenance Task Tracking",
  "Procurement & Inventory",
  "Paystack Payment Integration",
  "Invoices & Receipts",
  "Revenue & Analytics Dashboard",
  "Department Station Access Control",
  "Role-Based Staff Permissions",
  "Multi-Device / PWA Support",
  "OTA & Channel Manager (coming soon)",
  "Email & WhatsApp Notifications",
  "Priority 24/7 Support",
] as const;

export const HMS_FAQS = [
  {
    q: "What's included in the plan?",
    a: "Everything. XYVOO is a single, full-featured plan. No add-ons, no per-module fees. Every hotel on any cycle gets the complete platform.",
  },
  {
    q: "Can I switch billing cycles?",
    a: "Yes. You can upgrade from monthly to quarterly or yearly at any time. The difference will be prorated automatically.",
  },
  {
    q: "Is there a free trial?",
    a: "Yes — every new hotel gets a 14-day free trial with full access. No credit card required to start.",
  },
  {
    q: "How many rooms are supported?",
    a: "XYVOO supports unlimited rooms across all plans. Whether you have 10 rooms or 500, pricing stays the same.",
  },
  {
    q: "What payment methods are accepted?",
    a: "We accept all cards and bank transfers via Paystack, including Visa, Mastercard, and Verve.",
  },
  {
    q: "What happens at the end of my trial?",
    a: "You'll be prompted to choose a billing cycle. If you don't, the account goes into read-only mode — nothing is deleted.",
  },
];
